# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: | 
    dotnet restore CreditQueueListener.sln
    ls
  displayName: 'dotnet restore'


- script: | 
    dotnet build CreditQueueListener.sln
    ls
    cd /home/vsts/work/1/s/CreditQueueListener/bin/Debug/netcoreapp2.1/
    ls -al
    pwd
  displayName: 'dotnet build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '/home/vsts/work/1/s/CreditQueueListener/bin/Debug/netcoreapp2.1/'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: LambdaNETCoreDeploy@1
  inputs:
    awsCredentials: 'awsconnection'
    regionName: 'ap-south-1'
    command: 'deployFunction'
    packageOnly: false
    lambdaProjectPath: './CreditQueueListener'
    functionName: 'LoantoCreditor'
    functionRole: 'cloudform-LambdaExecutionRole-1XRKE2AES4R75'
    functionHandler: 'CreditQueueListener::CreditQueueListener.Function::FunctionHandler'
    functionMemory: 512
    functionTimeout: 60

- task: AWSCLI@1
  inputs:
    awsCredentials: 'awsconnection'
    regionName: 'ap-south-1'
    awsCommand: 'lambda'
    awsSubCommand: 'update-function-configuration'
    awsArguments: '--function-name LoantoCreditor --environment "Variables={Database=CreditApproval,Port=3306,PWD=admin8910,Server=applicationsubmission.cikv7fwlsku8.ap-south-1.rds.amazonaws.com,UID=admin}"'